config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :registrations, :controllers => { registrations: "registrations"}
  root to: 'restaurants#index'

  resources :users, only: [:show, :edit, :update]
  get 'user/:id/owner', to:'users#owner', as: :owner
  resources :restaurants do
  resources :bookings, except: [:edit, :update]
  end
  get 'restaurants/search/:q', to:'restaurants#search', as: :search
end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  def start_time
    self.booking_date ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_one :user
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_attachments :photos, maximum: 4

  validates :name, :municipality, :address, :capacity, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.search(query)
    if query.to_i != 0
      query = query.to_i
    end

    restaurants_results = []
    restaurant_name = []
    restaurant_municipality = []
    restaurant_category = []
    restaurant_capacity = []

    if query.is_a? Integer
      restaurant_capacity = where("capacity > #{query}")
    else
      restaurant_name = where("name LIKE ?", "%#{query}%")
      restaurant_municipality = where("municipality LIKE ?", "%#{query}%")
      restaurant_category = where("category LIKE ?", "%#{query}%")
    end

    unless restaurant_name.nil?
      restaurants_results += restaurant_name
    end

    unless restaurant_capacity.nil?
      restaurants_results += restaurant_capacity
    end

    unless restaurant_municipality.nil?
      restaurants_results += restaurant_municipality
    end

    unless restaurant_category.nil?
      restaurants_results += restaurant_category
    end

    return restaurants_results.uniq
  end

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :registration
  has_many :restaurants
  has_many :bookings
  has_attachment :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_registration!

  attr_reader :current_user
  helper_method :current_user

  def current_user
    @current_user ||= current_registration.try(:user)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_restaurant, only: [:booked_date, :show, :new, :create, :destroy]

  def show
    @booking = Booking.find(params.require(:id))
  end

  def new
    @available_booking = Booking.all - @restaurant.bookings
    @booking = Booking.new
  end

  def create
    unless current_user.last_name.nil? && current_user.first_name.nil?
      @booking = Booking.new(booking_params)
      @booking.user = current_user
      @booking.restaurant = @restaurant
      @booking.status = "Booked !"
       #if booking does no exists then(depending on the date) the user can book, else, not possible to book
      if booked_date.include?(@booking.booking_date)
        flash[:alert] = 'The date you picked is already booked. Please choose another date!'
        render 'bookings/new', alert: "test"
        # render 'bookings/new' action: :new, :alert => "You haz errors!"
      else
        @booking.save
        redirect_to user_path(current_user), alert: "Your booking has been saved!"
      end
    else
      redirect_to edit_user_path(current_user), alert: "Please complete your profile before booking "
    end
  end

  def destroy
    @booking = Booking.find(params.require(:id))
    @booking.destroy
    redirect_to user_path(current_user)
  end

  private

  def booked_date
    booked = []
    @restaurant.bookings.each do |booking|
      booked << booking.booking_date
    end
    return booked
  end

  def set_restaurant
    @restaurant = Restaurant.find(params.require(:restaurant_id))
  end

  def booking_params
    params.require(:booking).permit(:status, :booking_date, :user_id, :restaurant_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    super do
      User.create(registration_id: resource.id)
    end
  end

  protected

  def after_sign_up_path_for(resource)
    root_path
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_registration!, only: [:index, :show]
  before_action :set_restaurant, only: [:show, :edit, :destroy, :update]

  def search
    query = params[:search][:query]
    if query == ""
      @restaurants = Restaurant.all
    else
      @restaurants = Restaurant.search(query)
    end
    @restaurants_geo = @restaurants
    @hash = Gmaps4rails.build_markers(@restaurants_geo) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
    end
    render 'index', location: "restaurants"
  end

  def index
    @restaurants = Restaurant.all
    @restaurants_geo = Restaurant.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@restaurants_geo) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
    end
  end

  def show
    @hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    if @restaurant.save
      redirect_to user_path(current_user)
    else
      render 'form'
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to user_path(current_user)
    else
      render 'form'
    end
  end

  def destroy
    #code
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :municipality, :capacity, :category, :address, :user_id, photos: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:owner, :show, :edit, :update]

  def owner
    if @user.owner == false
      @user.owner = true
    else
      @user.owner = false
    end
    @user.save!
    redirect_to user_path(@user)
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render 'users/form'
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:owner, :last_name, :first_name, :phone_number, :registration_id, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([@restaurant,@booking]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :booking_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/new.html.erb
<div class="container">
  <h3 class="text-center">Book a reservation !</h3>

  <div class="container text-center" style="margin-bottom: 30px">
    <%= render 'form' %>
  </div>


  <h4 class="text-center">See below if dates are already booked</h4>
  <div class="container" id="calendar-user">
    <%= month_calendar events: @restaurant.bookings do |date, bookings| %>
    <%= date.day %>
    <% bookings.each do |booking| %>
      <div>
        <div class="event">
          <p>Already booked!</p>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

<div class="container text-center" style="margin-bottom: 30px">
  <%= link_to "Back", restaurant_path(@restaurant), class: "btn btn-info" %>
</div>

<% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>"><%= %></p>
<% end %>

app/views/bookings/show.html.erb
<h2 class="text-center"> Booking info </h2>


<div class="container" style="margin-bottom: 20px">
  <div class="row text-center box">
    <div class="col-md-3">
      <h3>Booker info</h3>
      <p><%= @booking.user.first_name %> <%= @booking.user.last_name %></p>
      <p><%= @booking.user.registration.email %></p>
    </div>
    <div class="col-md-3">
      <h3>Booker picture</h3>
      <%= cl_image_tag @booking.user.photo.path, class:"avatar-large"%>
    </div>
    <div class="col-md-3">
      <h3>Date</h3>
      <p><%= @booking.booking_date %></p>
    </div>
    <div class="col-md-3">
      <h3>Your restaurant</h3>
      <p><strong><%= @booking.restaurant.name %></strong></p>
      <p><%= @booking.restaurant.address %></p>
    </div>
  </div>
</div>

<div class="container">
<%= link_to "Back",  "#{user_path(current_user)}#calendar"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= yield(:title_tag).blank? ? "Book & Dine - Restaurants" : yield(:title_tag) %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>


    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>

    <%= cloudinary_js_config %>

    <%= yield(:after_js) %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>



<p>test local:3000</p>

app/views/restaurants/_form.html.erb
<%= simple_form_for([@restaurant]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :municipality %>
    <%= f.input :capacity %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :photos, as: :attachinary %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h3 class="text-center">Edit your restaurant here, upplaod a picture</h2>
        <p>ajouter du style ici aussi les gars !!!!</p>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<%= render 'shared/banner'  %>

<div class="main-container">
  <div style="margin-bottom: 100px;" class="container" id="restaurants">
    <div class="row">
      <%  @restaurants.each do |restau|%>
      <div class="col-xs-12 col-sm-4">
        <% unless restau.photos.empty? %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path restau.photos.first.path, height: 300, width: 400, crop: :fill %>')">
          <% else %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= asset_path "restaurant.jpg" %>')">
            <% end %>
            <div class="card-category"></div>
            <div class="card-description">
              <h2><%= restau.name %></h2>
              <p><%= restau.municipality %></p>
              <p><%= restau.category %></p>
              <p><%= link_to "More Info", restaurant_path(restau), class:"btn btn-info"%> </p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>

      <div id="map" class=" hidden-sm hidden-xs" style="width: 100%; height: 600px;"></div>

      <!--  maps Javascript google API -->
      <% content_for(:after_js) do %>
      <script type="text/javascript">
      $(document).ready(function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({internal: { id: 'map' }}, function() {
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          if (markers.length == 0) {
            handler.getMap().setZoom(2);
          } else if (markers.length == 1) {
            handler.getMap().setZoom(14);
          }
        });
      });
      </script>
      <% end %>
    </div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h3 class="text-center">Create a new restaurant</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<% if @restaurant.photos.any? %>

  <div class="banner show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @restaurant.photos.first.path%>')">
      <h2><%= @restaurant.name%></h2>
    </div>
      <div class="container">
      <div class="card-category"></div>
    </div>

    <div class="container">
      <div class="row text-center box">
        <div class="col-md-3">
          <h3>Address</h3>
          <p><%= @restaurant.address %></p>
        </div>
        <div class="col-md-3">
          <h3>Municipality</h3>
          <p><%= @restaurant.municipality %></p>
        </div>
        <div class="col-md-3">
          <h3>Capacity</h3>
          <p><%= @restaurant.capacity %></p>
        </div>
        <div class="col-md-3">
          <h3>Category</h3>
          <p><%= @restaurant.category %></p>
        </div>
      </div>

      <div class="row text-center">
        <%= link_to "Book this restaurant", new_restaurant_booking_path(@restaurant), class: "btn btn-primary btn-booking" %>
      </div>

    </div>

  <div style="margin-bottom: 100px;" class="container" id="restaurants">
    <div class="row">
      <%  @restaurant.photos.each do |photo|%>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path photo.path, height: 300, width: 400, crop: :fill %>')">


        </div>
      </div>
      <% end %>
    </div>
  </div>

<!-- if no photo has been uploaded yet, use the by default photo as a banner -->
<% else %>

  <div class="banner show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= asset_path "restaurant.jpg" %>')">
    <h2><%= @restaurant.name%></h2>
  </div>

  <div class="container">
    <div class="card-category"></div>
  </div>

  <div class="container">
    <div class="row text-center box">
      <div class="col-md-3">
        <h3>Address</h3>
        <p><%= @restaurant.address %></p>
      </div>
      <div class="col-md-3">
        <h3>Municipality</h3>
        <p><%= @restaurant.municipality %></p>
      </div>
      <div class="col-md-3">
        <h3>Capacity</h3>
        <p><%= @restaurant.capacity %></p>
      </div>
      <div class="col-md-3">
        <h3>Category</h3>
        <p><%= @restaurant.category %></p>
      </div>
    </div>

    <div class="row text-center">
      <%= link_to "Book this restaurant", new_restaurant_booking_path(@restaurant), class: "btn btn-primary btn-booking" %>
    </div>

  </div>

  <% end %>


<div id="map" style="width: 100%; height: 600px;"></div>
<% if @hash[0][:lat].nil? %>

<%= content_for(:after_js) do %>
<script type="text/javascript">
$(document).ready(function() {
  alert('The restaurant address was unfortunately not properly entered');
});
</script>
<% end %>

<% else %>

<% content_for(:after_js) do %>
<script type="text/javascript">
$(document).ready(function() {
  var handler = Gmaps.build('Google');
  var styles = [
    {
      "featureType": "landscape.man_made",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#f7f1df"
        }
      ]
    },
    {
      "featureType": "landscape.natural",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#d0e3b4"
        }
      ]
    },
    {
      "featureType": "landscape.natural.terrain",
      "elementType": "geometry",
      "stylers": [
        {
          "visibility": "off"
        }
      ]
    },
    {
      "featureType": "poi",
      "elementType": "labels",
      "stylers": [
        {
          "visibility": "off"
        }
      ]
    },
    {
      "featureType": "poi.business",
      "elementType": "all",
      "stylers": [
        {
          "visibility": "off"
        }
      ]
    },
    {
      "featureType": "poi.medical",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#fbd3da"
        }
      ]
    },
    {
      "featureType": "poi.park",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#bde6ab"
        }
      ]
    },
    {
      "featureType": "road",
      "elementType": "geometry.stroke",
      "stylers": [
        {
          "visibility": "off"
        }
      ]
    },
    {
      "featureType": "road",
      "elementType": "labels",
      "stylers": [
        {
          "visibility": "off"
        }
      ]
    },
    {
      "featureType": "road.highway",
      "elementType": "geometry.fill",
      "stylers": [
        {
          "color": "#ffe15f"
        }
      ]
    },
    {
      "featureType": "road.highway",
      "elementType": "geometry.stroke",
      "stylers": [
        {
          "color": "#efd151"
        }
      ]
    },
    {
      "featureType": "road.arterial",
      "elementType": "geometry.fill",
      "stylers": [
        {
          "color": "#ffffff"
        }
      ]
    },
    {
      "featureType": "road.local",
      "elementType": "geometry.fill",
      "stylers": [
        {
          "color": "black"
        }
      ]
    },
    {
      "featureType": "transit.station.airport",
      "elementType": "geometry.fill",
      "stylers": [
        {
          "color": "#cfb2db"
        }
      ]
    },
    {
      "featureType": "water",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#a2daf2"
        }
      ]
    }
  ];
  handler.buildMap({
    provider: {
      styles: styles
    },
    internal: { id: 'map' }
  }, function() {
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    if (markers.length == 0) {
      handler.getMap().setZoom(2);
    } else if (markers.length == 1) {
      handler.getMap().setZoom(14);
    }
  });
});
</script>
<% end %>

<% end %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(255, 240, 0, 0.2) 0%, rgba(46, 45, 35, 0.4) 50%), url(<%= image_path 'resto.jpg'%>);">
  <div class="banner-content">
    <h1>Book & Dine</h1>
    <p>Book a restaurant for your events</p>
    <%= render 'shared/search' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "#{root_path}", class: "navbar-wagon-brand" do %>
    <%= image_tag "chronos.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if registration_signed_in? %>

      <!-- Links when logged in -->

      <%= link_to "All Restaurants", "#{restaurants_path}#restaurants", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Dashboard", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <!-- remplacer la photo de sebastien Saunier et importer la GEM permettant a la personne d'importer des photos de profil -->
          <% if current_user.photo.nil? %>
            <%= image_tag "blank_user.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% else %>
            <%= cl_image_tag current_user.photo.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
            <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to restaurants_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_registration_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_registration_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% unless current_user.nil? %>
        <li><%= link_to edit_user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %></li>
        <% else  %>
        <% end  %>
        <li><%= link_to restaurants_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %></li>
        <li><%= link_to destroy_registration_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for :search, url: search_path(:search), :method => :get  do |f| %>
  <%= f.input :query , placeholder: "   name  category  municipality  capacity", label: false %>
  <%= f.submit "Search", class: "btn btn-info" %>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for([@user]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :phone_number %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.submit %>

  </div>
<% end %>

app/views/users/_owner.html.erb
<% if @user.owner == true  %>
<div class="container">
  <%= link_to "Don't be an owner anymore", owner_path(@user), class: "btn btn-info" %>
</div>
<% else  %>
<div class="container">
  <%= link_to "Become an owner", owner_path(@user), class: "btn btn-info" %>
</div>
<% end  %>

app/views/users/show.html.erb
<div class="container-fluid" style="padding: 0;">
  <div class="profile text-center" style="overflow: auto;">
    <div class="main">
      <div class="main-content">
        <% if current_user.photo.nil? %>
        <%= image_tag "blank_user.png", class: "avatar-large" %>
        <% else %>
        <%= cl_image_tag current_user.photo.path, class:"avatar-large"%>
        <% end %>
        <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
        <p><%= current_user.phone_number %></p>
        <p><%= current_user.registration.email %></p>
        <p><%=  %></p>
        <%= link_to "Edit info", edit_user_path(current_user), class: "btn btn-info" %>
        <% unless current_user.owner %>
        <div class="container">
          <h3>Become an owner</h3>
          <%= render 'owner'  %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="title-booking">
      <div class="title-content">
       <% if @user.owner %>
       <h2>My private bookings</h2>
       <% else %>
       <h2>My bookings</h2>
       <% end %>
     </div>
   </div>
   <div class="description" style="overflow: auto;">
    <% if current_user.bookings.any?%>
    <div class="container-fluid">
      <div class="row">
        <% @user.bookings.each do |booking| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card-mini" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= asset_path "restaurant.jpg" %>')">
            <h2><%= booking.restaurant.name %></h2>
            <h4><%= booking.booking_date %></h4>
            <p> <%= link_to "Cancel", restaurant_booking_path(booking.restaurant.id, booking.id), class: "btn btn-info", method: :delete, :data => {:confirm => 'Are you sure?'} %>
            </p>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <% else %>
    <p>No booking yet</p>
    <% end %>
  </div>
  <div class="container text-center">
    <%= link_to "New reservation","#{restaurants_path}#restaurants", class: "btn btn-primary" %>
  </div>
</div>


<% if @user.owner  %>
<div class="wrapper" style="margin: 30px auto; background: rgba(235, 235, 235, 0.95); display: block;">
  <div class="container">
    <div class="row spaced-header text-center">
      <h2>My restaurants</h2>
    </div>

    <% if current_user.restaurants.any?%>
    <div class="text-center box" style="margin-bottom: 20px;">
      <% @user.restaurants.each do |restaurant|  %>
      <div class="row">
        <div class="col-sm-3">
          <h3>Address</h3>
          <p><%= restaurant.address %></p>
        </div>
        <div class="col-sm-3">
          <h3>Capacity</h3>
          <p><%= restaurant.capacity %></p>
        </div>
        <div class="col-sm-3">
          <h3>Category</h3>
          <p><%= restaurant.category %></p>
        </div>
        <div class="col-sm-3">
          <%= link_to "Edit restaurant", edit_restaurant_path(restaurant), class: "btn btn-warning btn-centered" %>
        </div>
      </div>
      <% end  %>
    </div>
    <% else %>
    <p>No restaurant yet</p>
    <% end %>
    <div class="row">
      <%=  link_to "Add a restaurant", new_restaurant_path, class: "btn btn-primary" %>
    </div>

    <style>
    .spaced-header {
      padding: 50px 0px;
      font-weight: bold;
      letter-spacing: 15px;
    }
  </style>
  <div class="row text-center spaced-header">
    <h2>Calendar</h2>
  </div>
  <!--  calendar from the gem  https://github.com/excid3/simple_calendar#installation   -->
  <div class="row" style="padding-top: 50px;" id="calendar">
    <%= month_calendar events: @user.bookings do |date, bookings| %>
    <%= date.day %>
    <% bookings.each do |booking| %>
    <div>
      <div class="event">
        <%= link_to "#{booking.user.first_name} #{booking.user.last_name} at #{booking.restaurant.name}", restaurant_booking_path(booking.restaurant, booking), class: "link_to" %>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>
</div>
<% end  %>
</div>